[[main]]
  name = "Hjem"
  url = ""
  weight = -110

[[main]]
  name = "Fotos"
  url = "https://photo.veloce.dk/"
  weight = -109

[[main]]
  name = "Om"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/lillesoe"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/lillesoe"
[[social]]
  name = "instagram"
  weight = 3
  url = "https://www.instagram.com/lillesoe/"
[[social]]
  name = "linkedin"
  weight = 4
  url = "https://www.linkedin.com/in/lillesoe/"
[[social]]
  name = "rss"
  weight = 5
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"